---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jumpdir
      register: output
    - name: assert binary prints help output
      debug:
        msg: '{{ output.stdout }}'

