---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      jd_ver: v0.2.0
  tasks:
    - command: /usr/local/bin/jumpdir
      register: output
    - name: assert binary prints help output
      debug:
        msg: '{{ output.stdout }}'

