---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: '{{ ansible_env.HOME }}/.local/bin/jumpdir'
      register: output
    - name: assert binary prints help output
      debug:
        msg: '{{ output.stdout }}'
