---
# tasks file for jumpdir
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for {{ jd_install_dir }}
  become: yes
  stat:
    path: '{{ jd_install_dir }}'
  changed_when: False
  register: jd_binary
- when: not jd_binary.stat.exists
  block:
    - name: download {{ jd_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ jd_url }}'
        dest: '{{ jd_tmp_tgz }}'
        checksum: '{{ jd_checksum }}'
        mode: 0644
    - name: mkdir {{ jd_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ jd_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ jd_tmp_tgz }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ jd_tmp_tgz }}'
        dest: '{{ jd_install_dir }}'
        creates: '{{ jd_installed_exe }}'
  always:
    - name: rm {{ jd_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ jd_tmp_tgz }}'
        state: absent
- name: link {{ jd_installed_link }} to {{ jd_installed_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ jd_installed_exe }}'
    dest: '{{ jd_installed_link }}'
    state: link

