---
# tasks file for jumpdir
- name: install jumpdir binary
  include_role:
    name: bradfordwagner.go-releaser-install
  vars:
    gri_installs:
      - repo: bradfordwagner/go-cli-jumpdir
        tag: '{{ jd_ver }}'

- name: clone source {{ jd_repo }} into {{ jd_source_dir }}
  become: yes
  become_user: root
  git:
    repo: "{{ jd_repo }}"
    version: "{{ jd_ver }}"
    dest: "{{ jd_source_dir }}"

- name: completions {{ ansible_env.HOME }}
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK jumpdir"
    path: '{{ ansible_env.HOME }}/{{ item }}'
    create: true
    block: |
      source {{ jd_source_dir }}/hack/alias.sh
  loop:
    - .zshenv

