---
# tasks file for jumpdir
- name: ensure {{ jd_gri_link_dir }} exists
  file:
    path: '{{ jd_gri_link_dir }}'
    state: directory
    mode: '755'

- name: install jumpdir binary
  include_role:
    name: bradfordwagner.go-releaser-install
  vars:
    gri_parent_install_dir: '{{ jd_gri_parent_install_dir }}'
    gri_link_dir: '{{ jd_gri_link_dir }}'
    gri_installs:
      - repo: bradfordwagner/go-cli-jumpdir
        binary_name: jumpdir
        tag: '{{ jd_ver }}'

- name: clone source {{ jd_repo }} into {{ jd_source_dir }}
  git:
    repo: "{{ jd_repo }}"
    version: "{{ jd_ver }}"
    dest: "{{ jd_source_dir }}"

- name: completions {{ ansible_env.HOME }}
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK jumpdir"
    path: '{{ ansible_env.HOME }}/{{ item }}'
    create: true
    block: |
      source {{ jd_source_dir }}/hack/alias.sh
  loop:
    - .zshenv

